### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by slidenerd** [GanadiniAkshay/ApiAiRecognizer#1]
just wanted to give you a headsup, i searched for api.ai on botbuilder repo and came across your open issue. I quickly came to your GitHub profile and saw the api.ai module for botframework 👍 Testing now

**Comment by GanadiniAkshay** [comment]
@slidenerd let me know if you find issues or have suggestions

**Comment by slidenerd** [comment]
A few suggestions quickly off the back 

1. Small talk intents seem to have an issue 
2. You should be using conversationId as the session id for api.ai
