### ISSUE TITLE
"Using Prompts" example missing

### ISSUE THREAD

**Issue by erickriva** [GanadiniAkshay/ApiAiRecognizer#4]
On **Using Prompts** section, do you say: 

> You can use prompts provided by api.ai for required entities very easily. Just check the actionIncomplete entity from the entities list and if its true use the fulfillment to send out the prompt.

do you have a example?

**Comment by GanadiniAkshay** [comment]
will add some documentation in the readme

**Comment by amitbend** [comment]
@GanadiniAkshay can you add an example please?

**Comment by slidenerd** [comment]
Any updates on this?

**Comment by slidenerd** [comment]
Ok I went through the source code and got it. Notice how he has intialized these arrays
```
                    const entities_found = [
                        {
                            entity: result.fulfillment.speech,
                            type: 'fulfillment',
                            startIndex: -1,
                            endIndex: -1,
                            score: 1
                        },
                        {
                            entity: result.actionIncomplete,
                            type: 'actionIncomplete',
                            startIndex: -1,
                            endIndex: -1,
                            score: 1
                        }
                    ];
```

meaning inside your dialog, you can simply find them
`let incomplete = (builder.EntityRecognizer.find(args.entities, 'actionIncomplete') || {}).entity || []`

That should do the job

**Comment by GanadiniAkshay** [comment]
@slidenerd thanks for the explanation

@amitbend I have added an example in the Readme as well in commit [f688e25](https://github.com/GanadiniAkshay/ApiAiRecognizer/commit/f688e254bc621e00d9e8bda34c3029ed436514cf)
