### ISSUE TITLE
sessionId exceeding 36 characters

### ISSUE THREAD

**Issue by isnehasish** [GanadiniAkshay/ApiAiRecognizer#7]
Line 12 - 16 index.js --- there is no length check on sessionId. Sometimes channel_id+user_id > 36 characters, which causes api.ai to error out. One such scenario is when your client is Cortana. Requests from Cortana are failing for sessionId > 36 characters.

**Comment by GanadiniAkshay** [comment]
that should be a simple fix...we could hash the channel_id + user_id to have a constant length for session_id.
Will push out a fix ASAP

**Comment by GanadiniAkshay** [comment]
Used first 36 chars when limit exceeded...that should be fine for now
